#!/bin/sh
current_branch=`git branch | grep '*' | sed 's/* //'`

if [ "$current_branch" = "main" ]; then
    echo "About to commit! Wish me luck."
    python3 test.py
    if [ $? -eq 0 ]; then
        # tests passed, proceed to prepare commit message
        exit 0
    else
        # some tests failed, prevent from committing broken code on main
        echo "Failure! Try to fix it! P.S. - You can still commit though."
        exit 1
    fi
fi
